apiVersion: batch/v1
kind: CronJob
metadata:
  name: merge-data-daily
spec:
  schedule: "30 8 * * 1-5"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: merger
            image: us-central1-docker.pkg.dev/market-oracle-tesis/market-oracle/market-oracle:release
            imagePullPolicy: Always
            command: ["python", "src/features/merge_data.py"]
            env:
            - name: PYTHONPATH  # ðŸ‘ˆ Â¡Esta es la clave!
              value: "/app"
            - name: GCP_PROJECT_ID
              value: "market-oracle-tesis"
            - name: GCP_BUCKET_NAME
              value: "market-oracle-tesis-data-lake"
            resources:
              requests:
                cpu: "100m"
                memory: "512Mi"
          restartPolicy: OnFailure
